### ISSUE TITLE
Design LDAP permissions and make puppet set them up

### ISSUE THREAD

**Issue by ingomueller-net** [AEGEE/oms-development-vm#20]
We should find out how LDAP permissions are correctly done. Probably we should base ourselves on what Wim does at the moment. Then puppet should set these permissions.

---
- Bitbucket: https://bitbucket.org/ingomueller-net/ldap-poc/issue/20
- Originally reported by: Ingo Müller
- Originally created at: 2015-10-26T14:27:11.516

**Comment by ingomueller-net** [comment]
Not having done that yet probably causes #6.

----------------------------------------
Original comment by: Ingo Müller

**Comment by ingomueller-net** [comment]
we can ask Wim an export of ACLs (Access Control Logics) and see what we can reuse

----------------------------------------
Original comment by: [grasshopper](http://bitbucket.org/grasshopper)

**Comment by serviceman** [comment]
From his email:

basically, everybody has read access to his own data, and not to others. Everybody has access to all group information. Few accounts have read access to all data, basically used for exports. And there is one account with write access, used by the tool that transfers the data from intranet MySQL to LDAP.

I didn't put the code here because trivial to reproduce
