### ISSUE TITLE
Upgrading npm does not upgrade /usr/bin/npm

### ISSUE THREAD

**Issue by linuxbandit** [AEGEE/oms-development-vm#35]
The upgrade creates a new instance of npm in /usr/local/bin/npm.

Check scripts/upgrade_node-npm.sh

**Comment by serviceman** [comment]
more precisely:

```
vagrant@aegee-virtual:/usr$ /usr/bin/npm version
{ npm: '2.14.15',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '46',
  node: '4.1.2',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
vagrant@aegee-virtual:/usr$ /usr/local/bin/npm version
{ npm: '2.14.4',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '46',
  node: '4.1.2',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
vagrant@aegee-virtual:/usr$ which npm
/usr/local/bin/npm
```

So, having 2 version is uncool already; additionally the local/bin version is not the target one (2.14.4 instead of 2.14.15). For some reason after the upgrade npm is updated to use /usr/local/bin, because at one checkpoint during the provisioning I could be sure that 

```
$ which npm
/usr/bin/npm
```

**Comment by serviceman** [comment]
Note that I tried as per [here](https://docs.npmjs.com/getting-started/fixing-npm-permissions):

```
npm config set prefix '/usr/bin'
```
with no avail, even specifying for both 
```
/usr/local/bin/npm config set prefix '/usr/bin'
/usr/bin/npm config set prefix '/usr/bin'
```

This solution attempt causes puppet to fail on the upstart of the service, because the system cannot find forever. Even playing it dirty and trying 
```
npm install -g forever
```

Won't do the trick. So for now there's no simple fix that can be done touching scripts/upgrade_node-npm.sh
